### PR TITLE
the light at the end of the tunnel

### PR DESCRIPTION
**Pull request by aleksandra-novozhilova**

### CODE REVIEW

**Comment by neurorepro** [comment]
@aleksandra-novozhilova my apologies but there is a very last step you have to do: resolve the merge conflict as the repo was updated (cf `README` for instructions). Almost there !

**Comment by aleksandra-novozhilova** [comment]
I thought I had resolved this when i put my name after David idk why it doesn't show up now.

**Comment by neurorepro** [comment]
@aleksandra-novozhilova there were "simultaneous" PR requests from you and Nicolas Piron, so somehow Nicolas Piron's PR got in, and now you have to update yours to include Piron's changes. Please note that this is a common scenario and that's why we saw merge conflict in the course. You have instructions in the `README` on how to deal with this.

**Comment by neurorepro** [comment]
Congrats !!

**Comment by aleksandra-novozhilova** [comment]
thank you !

**Pull request merged**
